services:
  asset-dashboard-api:
    image: ghcr.io/alenkoikkara/asset-dashboard-backend:latest
    container_name: asset-dashboard-apid
    command: uvicorn api.main:app --host 0.0.0.0 --port 8002
    env_file: .env
    volumes:
      - asset_dashboard_data:/app/data
    ports:
      - "8002:8002"
    restart: unless-stopped
    networks:
      - app-network

volumes:
  asset_dashboard_data:
    name: asset_dashboard_data

networks:
  app-network:
    external: true
